language: node_js
node_js:
  - "6.11.2"
before_script:
  - npm i -g npm@3.10.10
  - npm install -g gulp-cli
  - npm install
script:
  - gulp
  - bash ./out.sh
deploy:
  provider: pages
  local-dir: out
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  target-branch: gh-pages
  on:
    branch: master
